import '../globals.css';
import type { Metadata } from 'next';
import { Manrope } from 'next/font/google';

const inter = Manrope({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
};

export default function RootLayout({
	children
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body
				className={` bg-gradient-to-r from-bg-primary to-bg-primary overflow-x-hidden ${inter.className}`}
			>
				<div className="w-screen h-100 container mx-auto my-10">{children}</div>
			</body>
		</html>
	);
}
